### ISSUE TITLE
Require Drupal Console

### ISSUE THREAD

**Issue by skounis** [openeuropa/oe_webtools#117]
Its nice to have the commands drupal console provide available. Especially the `site:mode`

**Comment by brummbar** [comment]
Drupal console should be a dev dependency on your project and not on the component.

**Comment by skounis** [comment]
@brummbar It makes sense, however why we keep `drush` as a dev dependency on the component and not `drupal/console`?

**Comment by brummbar** [comment]
Because Drush is needed for tasks like [installing the modules from command line](https://github.com/openeuropa/oe_webtools/blob/master/runner.yml.dist#L19).

**Comment by skounis** [comment]
From this point of view the handy way "drupal/console" provides to switch to development mode and disable caching could not be considered significant part of the development?

**Comment by brummbar** [comment]
No, you are missing the point. `drush/drush` is a required development dependency to:
* prepare the development setup of **this** component;
* test **this** component.
In the require-dev of **this** component only dependencies regarding the development of this component should go. `drupal/console` is not needed to work in the component.
