### ISSUE TITLE
Drupal 9 support

### ISSUE THREAD

**Issue by didierdemaeyer** [openeuropa/oe_webtools#153]
### Description

Add support for Drupal 9.

### Additional information

Upgrade Status report:
[single-export-oe_webtools-2021-03-19T14_21_51+0100.txt](https://github.com/openeuropa/oe_webtools/files/6171652/single-export-oe_webtools-2021-03-19T14_21_51%2B0100.txt)

**Comment by LOBsTerr** [comment]
PR: https://github.com/openeuropa/oe_webtools/pull/155
