### ISSUE TITLE
 oe_webtools_analytics seems not be compatible with 8.1 PHP version

### ISSUE THREAD

**Issue by jblanmar** [openeuropa/oe_webtools#202]
Dear Team,

In our project, we have installed version PHP 8.1 and we are getting the following error related oe_webtools_analytics:

_Deprecated: Return type of Drupal\oe_webtools_analytics\Event\AnalyticsEvent::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/ec2-user/environment/cinea-bridge-reference/web/modules/contrib/oe_webtools/modules/oe_webtools_analytics/src/Event/AnalyticsEvent.php on line 243_

Are you planning to update the module to be compatible with PHP 8.1 o could you indicate us how to proceed? 

Thank you in advance.

Best regards,

Jose.

**Comment by alesrebec** [comment]
@jblanmar Fixed in PR #205 
Please, feel free to test it 

@ mantainers - lets get it released ASAP because in 4 days PHP 7.4 is EOL.

**Comment by brummbar** [comment]
Fixed in #209.
