### ISSUE TITLE
Webtools Sliding Captcha integration

### ISSUE THREAD

**Issue by cor-emble** [openeuropa/oe_webtools#203]
Hi all,

I've created a small custom module for a EC project we maintain which implements the Webtools Sliding captcha on Drupal forms. 

It is build on the Captcha API module https://www.drupal.org/project/captcha so you could add the captcha on all forms supported by the Captcha module like Webforms. 

Would love to share it but should this be part of the webtools module or should we create a new repository?

**Comment by brummbar** [comment]
Hello @cor-emble , that sounds incredibly nice! Can you open a pull request with the code? If it's well isolated it can be a submodule.
