### ISSUE TITLE
Webtools modules - Migration from europa.eu/webtools to webtools.europa.eu

### ISSUE THREAD

**Issue by alexboss** [openeuropa/oe_webtools#233]
Dear colleagues,

Following CEM communication:

> This update follows a previous communication: [Webtools - Move widgets and services to the cloud (CORRIGENDUM)](https://ec.europa.eu/newsroom/cem/newsletter-archives/51845).
> Reminder
> The migration implies a change in the URL of the Webtools endpoints:
> https://europa.eu/webtools will become https://webtools.europa.eu/
> New important information
> The migration of Webtools to the cloud cannot be done without downtime and as a result, all [Smart Loader (SML)](https://webgate.ec.europa.eu/fpfis/wikis/display/webtools/SmartLoader+-+API) components will be unavailable. Webtools widgets (maps, charts, etc.) may stop working on Monday 15 April between 6:00 and 7:00 AM.
> Updated information
> If you use the Webtools endpoints listed in this [Excel file](https://ec.europa.eu/newsroom/repository/document/2024-12/Webtools__Cloud_migration__New_endpoints_4PNrxzUHG9JXXUhD3WcBdM321UU_103746.xlsx) on your websites and applications, please update them within 48 hours after the migration or before Wednesday 17 April at 9:00 AM.
> If you do not use any of the specific endpoints from the [Excel file](https://ec.europa.eu/newsroom/repository/document/2024-12/Webtools__Cloud_migration__New_endpoints_4PNrxzUHG9JXXUhD3WcBdM321UU_103746.xlsx) on your websites and applications, no action is expected from you.
> After the migration, if ever you detect issues with your Webtools widgets and services, please report them via the [Europa Web Communication](https://digit.service-now.com/esc?id=emp_taxonomy_topic&topic_id=e2bcc0f38721fd50dd76873e8bbb35da) form.

For modules using Webtools endpoint using GET, there's plenty of time to migrate (a redirection will be put in place).

However, for modules using POST, the replacement of URL will have to be made quite urgently.

The  `oe_webtools_captcha` is impacted by the migration.

See https://github.com/openeuropa/oe_webtools/blob/master/modules/oe_webtools_captcha/config/install/oe_webtools_captcha.settings.yml

```
validationEndpoint: 'https://europa.eu/webtools/rest/captcha/verify' 
```

Using POST method - see https://github.com/openeuropa/oe_webtools/blob/master/modules/oe_webtools_captcha/oe_webtools_captcha.module :

```
       $response = \Drupal::httpClient()->post($url->toString(), [
        'headers' => $headers,
        'form_params' => $params,
      ]);
```

So the `validationEndpoint` should be:
```
validationEndpoint: 'https://webtools.europa.eu/rest/captcha/verify' 
```

And the switch should:
> please update them within 48 hours after the migration or before Wednesday 17 April at 9:00 AM.

Thank you and best regards.

Alexandre

**Comment by nagyad** [comment]
This had been addressed in: https://github.com/openeuropa/oe_webtools/pull/234.
