### ISSUE TITLE
Need to define siteID for dev installation

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/oe_webtools#25]
After installing the site we have this recurrent warning message in logs:
The setting "siteID" is missing from settings file.

This information could be shown in the status report, because as it is the error is generated each time Analytics event is fired.

Also, the test to generate the message is if the siteId is numeric. So it doesn't match very well with the message. After PR #23 it shouldn't mention the "settings file", because this setting can be configured in admin page.

**Comment by voidtek** [comment]
To solve this issue: 
- We can create the install config file (and a hook_update) to initialize all configuration - `oe_webtools_analytics.settings.yml`.

- We can change the message, or remove it if not helpful for the site builder or spamming the log.

**Comment by sergepavle** [comment]
Looks like already resolved
