### ISSUE TITLE
OPENEUROPA-1633: Provide priorities for analytics rules

### ISSUE THREAD

**Issue by pfrenssen** [openeuropa/oe_webtools#38]
It is possible that there are multiple rules that match a given path. If this is the case we should allow administrators to define which rule should be used.

Let's say for example the following three rules are defined:

| Expression | Section |
| --- | --- |
| `\|^/admin/\|` | Site administration |
| `\|^/admin/config/\|` | Site configuration |
| `\|^/admin/config/search/\|` | Search configuration |

If the user is on the path `/admin/config/search/path/patterns` then the best match is the "Search configuration" section and not the generic "Site administration".

There are different ways to provide this prioritisation and we could make it very advanced, but for an initial version it could be as simple as providing a drag & drop functionality that allows the administrators to reorder the rules, and put the higher priority ones at the top.

**Comment by sergepavle** [comment]
PR https://github.com/openeuropa/oe_webtools/pull/60

**Comment by brummbar** [comment]
This has been fixed with PR #60 .
