### ISSUE TITLE
Add oe_webtools dependency to oe_webtools_social_share

### ISSUE THREAD

**Issue by vever001** [openeuropa/oe_webtools#47]
Hello,

After enabling oe_webtools_social_share on my website, the share buttons block was not showing up because it was missing the library defined in oe_webtools.

A dependency to oe_webtools should probably be added to oe_webtools_social_share and possibly other sub-modules.

Thanks,
Hervé

**Comment by brummbar** [comment]
You are absolutely correct, thanks for reporting 😄
